CREATE TABLE IF NOT EXISTS snippets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  language VARCHAR(50) NOT NULL,
  stdin TEXT NOT NULL,
  source_code TEXT NOT NULL,
  submission_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
